language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_script: greenkeeper-lockfile-update
script:
  - nyc --reporter=lcov npm test
  - codecov
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
