language: node_js
cache: npm
node_js:
  - 11.10
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email:
    recipients:
      - saiichihashimoto@gmail.com
    on_success: never
    on_failure: always
env:
  -
  - MONGOOSE_VERSION="5.0.0"
  - MONGOOSE_VERSION="^4.0.0"
  - MONGOOSE_VERSION="4.0.4"
  - MONGOOSE_VERSION="~3.8.0"
  - MONGOOSE_VERSION="3.2.2"
  - NORMALIZR_VERSION="3.0.0"
  - NORMALIZR_VERSION="^2.0.0"
  - NORMALIZR_VERSION="2.0.0"
  - NORMALIZR_VERSION="^1.0.0"
  - NORMALIZR_VERSION="1.0.0"
  - NORMALIZR_VERSION="^0.1.1"
  - NORMALIZR_VERSION="0.1.1"
before_script:
  - [ ! -z "$MONGOOSE_VERSION" ] && npm install mongoose@"$MONGOOSE_VERSION" --no-save
  - [ ! -z "$NORMALIZR_VERSION" ] && npm install normalizr@"$NORMALIZR_VERSION" --no-save
after_success:
  - cat ./coverage/lcov.info | npx coveralls
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
