language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - nyc --reporter=lcov npm test
  - codecov
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
