language: node_js
cache: npm
node_js:
  - 11.10
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email:
    recipients:
      - saiichihashimoto@gmail.com
    on_success: never
    on_failure: always
after_success:
  - cat ./coverage/lcov.info | npx coveralls --verbose
jobs:
  include:
    - stage: test
    - env: MONGOOSE_VERSION="5.0.0"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
    - env: MONGOOSE_VERSION="^4.0.0"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
    - env: MONGOOSE_VERSION="4.0.4"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
    - env: MONGOOSE_VERSION="~3.8.0"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
    - env: MONGOOSE_VERSION="3.2.2"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
    - env: NORMALIZR_VERSION="3.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
    - env: NORMALIZR_VERSION="^2.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
    - env: NORMALIZR_VERSION="2.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
    - env: NORMALIZR_VERSION="^1.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
    - env: NORMALIZR_VERSION="1.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
    - env: NORMALIZR_VERSION="^0.1.1"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
    - env: NORMALIZR_VERSION="0.1.1"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"

    - stage: release
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
