language: node_js
node_js:
  - 11
env:
  -
  - MONGOOSE_VERSION="5.0.0"
  - MONGOOSE_VERSION="^4.0.0"
  - MONGOOSE_VERSION="4.0.3"
  - NORMALIZR_VERSION="3.0.0"
  - NORMALIZR_VERSION="^2.0.0"
  - NORMALIZR_VERSION="2.0.0"
  - NORMALIZR_VERSION="^1.0.0"
  - NORMALIZR_VERSION="1.0.0"
  - NORMALIZR_VERSION="^0.1.1"
  - NORMALIZR_VERSION="0.1.1"
before_script:
  - if [ ! -z ${MONGOOSE_VERSION+x} ]; then npm install mongoose@"$MONGOOSE_VERSION"; fi
  - if [ ! -z ${NORMALIZR_VERSION+x} ]; then npm install normalizr@"$NORMALIZR_VERSION"; fi
after_success:
  - npx codecov
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
