language: node_js
node_js:
  - 11
after_success:
  - npx codecov
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
