language: node_js
node_js:
  - 11
after_success:
  - npx codecov
jobs:
  include:
    - stage: test

    - stage: mongoose
      env: MONGOOSE_VERSION="5.0.0"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
      after_success:  npx codecov
    - env: MONGOOSE_VERSION="^4.0.0"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
      after_success: npx codecov
    - env: MONGOOSE_VERSION="4.0.4"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
      after_success: npx codecov
    - env: MONGOOSE_VERSION="~3.8.0"
      before_script: npm install mongoose@"$MONGOOSE_VERSION"
      after_success: npx codecov

    - stage: normalizr
      env: NORMALIZR_VERSION="3.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
      after_success: npx codecov
    - env: NORMALIZR_VERSION="^2.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
      after_success: npx codecov
    - env: NORMALIZR_VERSION="2.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
      after_success: npx codecov
    - env: NORMALIZR_VERSION="^1.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
      after_success: npx codecov
    - env: NORMALIZR_VERSION="1.0.0"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
      after_success: npx codecov
    - env: NORMALIZR_VERSION="^0.1.1"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
      after_success: npx codecov
    - env: NORMALIZR_VERSION="0.1.1"
      before_script: npm install normalizr@"$NORMALIZR_VERSION"
      after_success: npx codecov

    - stage: release
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
