language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
env:
  - NODE_ENV=test
node_js:
  - '9'
  - '8'
before_script: greenkeeper-lockfile-update
script:
  - npm run coverage:test
after_success:
  - npm run semantic-release
after_script: 
  - greenkeeper-lockfile-upload
  - npm run coverage:report
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
