language: node_js
node_js:
  - 11
env:
  - NORMAL=true
  - MONGOOSE_VERSION=0 NORMALIZR_VERSION=0
  - MONGOOSE_VERSION=0 NORMALIZR_VERSION=1
  - MONGOOSE_VERSION=0 NORMALIZR_VERSION=2
  - MONGOOSE_VERSION=0 NORMALIZR_VERSION=3
  - MONGOOSE_VERSION=1 NORMALIZR_VERSION=0
  - MONGOOSE_VERSION=1 NORMALIZR_VERSION=1
  - MONGOOSE_VERSION=1 NORMALIZR_VERSION=2
  - MONGOOSE_VERSION=1 NORMALIZR_VERSION=3
  - MONGOOSE_VERSION=2 NORMALIZR_VERSION=0
  - MONGOOSE_VERSION=2 NORMALIZR_VERSION=1
  - MONGOOSE_VERSION=2 NORMALIZR_VERSION=2
  - MONGOOSE_VERSION=2 NORMALIZR_VERSION=3
  - MONGOOSE_VERSION=3 NORMALIZR_VERSION=0
  - MONGOOSE_VERSION=3 NORMALIZR_VERSION=1
  - MONGOOSE_VERSION=3 NORMALIZR_VERSION=2
  - MONGOOSE_VERSION=3 NORMALIZR_VERSION=3
  - MONGOOSE_VERSION=4 NORMALIZR_VERSION=0
  - MONGOOSE_VERSION=4 NORMALIZR_VERSION=1
  - MONGOOSE_VERSION=4 NORMALIZR_VERSION=2
  - MONGOOSE_VERSION=4 NORMALIZR_VERSION=3
  - MONGOOSE_VERSION=5 NORMALIZR_VERSION=0
  - MONGOOSE_VERSION=5 NORMALIZR_VERSION=1
  - MONGOOSE_VERSION=5 NORMALIZR_VERSION=2
  - MONGOOSE_VERSION=5 NORMALIZR_VERSION=3
before_script:
  - if [ -z "$NORMAL" ]; then npm install mongoose@"^$MONGOOSE_VERSION" normalizr@"^$NORMALIZR_VERSION" ; fi
after_success:
  - npx codecov
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build && npx semantic-release
